// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwlZa89RDt10D0EGt09uCAmaf0ACzZ7iU',
    appId: '1:993551613000:web:22d007af2f0fdae9716c7d',
    messagingSenderId: '993551613000',
    projectId: 'fir-87987',
    authDomain: 'fir-87987.firebaseapp.com',
    storageBucket: 'fir-87987.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEGlimGptvsnsIEa-tRoF9Q9-HrG1gcrw',
    appId: '1:993551613000:android:e8a919575a50457a716c7d',
    messagingSenderId: '993551613000',
    projectId: 'fir-87987',
    storageBucket: 'fir-87987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSiBDpj5hSVLtWHIy9aSDqH3KNyNYI8x4',
    appId: '1:993551613000:ios:c20ae883f93d9fe7716c7d',
    messagingSenderId: '993551613000',
    projectId: 'fir-87987',
    storageBucket: 'fir-87987.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSiBDpj5hSVLtWHIy9aSDqH3KNyNYI8x4',
    appId: '1:993551613000:ios:59076244fe150547716c7d',
    messagingSenderId: '993551613000',
    projectId: 'fir-87987',
    storageBucket: 'fir-87987.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
